### ISSUE TITLE
KVM does not abide by user consent settings, and resets upon use

### ISSUE THREAD

**Issue by CIMAEnergy** [open-amt-cloud-toolkit/sample-web-ui#1208]
Latest version (06-23)
Built profile with user consent required for KVM
device showed up with new profile, but user consent set to none.
Connected to KVM without consent prompt.

Went back out, set kvm consent in gui on the device
Initially, after refresh, consent was none, but after a short period of time it did reflect "KVM"

Connected to KVM, without consent being asked/required - device setting was reverted back to none.

**Comment by bwendlandt-intel** [comment]
Hello, this fix was closed in #1328 and released as part of v2.13.1 of the Sample Web UI. Please pull or build the latest image for the changes to take affect. Thanks!
