### ISSUE TITLE
Please remove the snow effect. It wastes a lot of resources.

### ISSUE THREAD

**Issue by rgl** [open-amt-cloud-toolkit/sample-web-ui#1615]
Please remove the snow introduced in https://github.com/open-amt-cloud-toolkit/sample-web-ui/releases/tag/v3.5.0. Here the browser is wasting precious resources showing all the  192 snow balls around.

**Comment by rsdmike** [comment]
Hey @rgl, this will be removed in the next release. Until then, please use the previously tagged release to avoid the winter wonderland. Happy new year!
