### ISSUE TITLE
[Sample-Web-UI] Show Network settings in Device Details Page of Console

### ISSUE THREAD

**Issue by graikhel-intel** [open-amt-cloud-toolkit/sample-web-ui#2041]
As a console user, I want to see Network information in Device details page.

###  Wired Interface Info
- [ ] Link Status
- [ ] Link Policy
- [ ] MAC address
- [ ] IPv4 address
- [ ] Gateway
- [ ] Subnet Mask
- [ ] DNS
- [ ] IP synchronization status
- [ ] Wired 8021x Information
  - [ ] Enabled
  - [ ] Protocol
  - [ ] Server
  - [ ] Domain
  - [ ] Username
  - [ ] Client Certificate
  - [ ] Server Certificate
  - [ ] Active in S0
  - [ ] PXE Timeout

### Wireless Interface
- [ ] Link Status
- [ ] Link Policy
- [ ] State
- [ ] Radio State
- [ ] MAC address
- [ ] IPv4 address
- [ ] Gateway
- [ ] Subnet Mask
- [ ] DNS
- [ ] Local WIFI profile sync
- [ ] Show all the wireless profiles synced with AMT
  - [ ] Profile1
  - [ ] Profile2

Each wireless profile can also has 8021x information linked

**Comment by rsdmike** [comment]
open-amt-cloud-toolkit/sample-web-ui#2043
open-amt-cloud-toolkit/console#290
