### ISSUE TITLE
Issue while logging into RPS through Open AMT Cloud Toolkit Sample UI

### ISSUE THREAD

**Issue by viharigandrakota** [open-amt-cloud-toolkit/sample-web-ui#234]
Hi, 

I deployed Intel AMT cloud toolkit microservices on Azure container instances by following [this](https://portal.azure.com/#create/Microsoft.Template). The container instance got created and I can see all 6 containers running. However, when I use the FQDN to open the Web-UI and give the default username and password found [here](https://open-amt-cloud-toolkit.github.io/docs/1.1/General/loginToRPS/) i am hitting an error : "ERROR LOGGING IN" . 

I followed instructions given [here](https://open-amt-cloud-toolkit.github.io/docs/1.3/Docker/dockerCloud/) to build MPS and RPS images and used `docker build -t <tag> .` command to build the sample Web-UI image. 

Could you please help us?

**Comment by rsdmike** [comment]
@viharigandrakota Can you send me a screenshot with the network tab open in your browser? Please make sure you are using "https://FQDN:8443" and not http.

**Comment by matt-primrose** [comment]
@viharigandrakota we haven't seen any activity on this issue in a while.  Please re-open the issue if you are still seeing this issue and have more information.
