### ISSUE TITLE
Logging out of Sample-Web-UI page while on an active KVM session does not take user back to login page

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/sample-web-ui#283]
Steps to reproduce:

1. Start a KVM session on a device
2. Press the logout button for the Sample Web UI page
3. User will see a white screen

Expected behavior: user is taken back to the login screen

**Comment by vyshali-chitikeshi** [comment]
Not able to replicate the issue with latest code, closing it.
